### ISSUE TITLE
Editing or deleting messages skype-> discord doesn't work.

### ISSUE THREAD

**Issue by Ashymad** [Infiziert90/Discord-Skype-Bot#1]
It seems that with https://github.com/Infiziert90/Discord-Skype-Bot/commit/7c6b8f00c2ae82a98c2a0ef8c7c59db45c9eba0c this regression has been introduced.
Traceback:
```Traceback (most recent call last):
  File "/home/shyman/.pyenv/versions/3.6.2/lib/python3.6/concurrent/futures/thread.py", line 55, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/home/shyman/.pyenv/versions/skycord/lib/python3.6/site-packages/skpy/main.py", line 207, in cycle
    self.onEvent(event)
  File "./skype-bot.py", line 68, in onEvent
    content, sky_file = self.EditMessage.inspect_skype_content_edit(event.msg)
ValueError: not enough values to unpack (expected 2, got 0)

**Comment by Infiziert90** [comment]
Update your message_edit.py with the new version and it should work without any problem.

**Comment by Ashymad** [comment]
Thank you 👍
