### ISSUE TITLE
Skype-get.py doesn't read configuration file

### ISSUE THREAD

**Issue by Rixxan** [Infiziert90/Discord-Skype-Bot#3]
OS: Windows 10 Pro. All dependancies recently installed.
Upon running skype-get.py, the following appears:

Traceback (most recent call last):
  File "F:\*****\Downloads\Discord-Skype-Bot-master\skype-get.py", line 31, in <module>
    main()
  File "F:\*****\Downloads\Discord-Skype-Bot-master\skype-get.py", line 16, in main
    load_config()
  File "F:\*****\Downloads\Discord-Skype-Bot-master\config\__init__.py", line 78, in load_config
    raise ImproperlyConfigured("No configuration file found.")
config.ImproperlyConfigured: No configuration file found.

**Comment by Ashymad** [comment]
Do You have a configuration file? You should create `skype-bot.ini`. There is an example in repository (`skype-bot-example.ini`).

**Comment by Rixxan** [comment]
I hadn't renamed the default INI file, but now this appears when I run the file:

Command: C:\Users\*****>python F:\Rixxan\Downloads\Discord-Skype-Bot-master\skype-get.py
```
Traceback (most recent call last):
  File "F:\*****\Downloads\Discord-Skype-Bot-master\skype-get.py", line 31, in <module>
    main()
  File "F:\*****\Downloads\Discord-Skype-Bot-master\skype-get.py", line 16, in main
    load_config()
  File "F:\*****\Downloads\Discord-Skype-Bot-master\config\__init__.py", line 107, in load_config
    emoji_dict = json.load(emoji_json)
  File "F:\Users\*****\AppData\Local\Programs\Python\Python36\lib\json\__init__.py", line 296, in load
    return loads(fp.read(),
  File "F:\Users\*****\AppData\Local\Programs\Python\Python36\lib\encodings\cp1252.py", line 23, in decode
    return codecs.charmap_decode(input,self.errors,decoding_table)[0]
UnicodeDecodeError: 'charmap' codec can't decode byte 0x81 in position 6953: character maps to <undefined>


```

**Comment by Infiziert90** [comment]
Update your bot with the newest version from git and the problem is fixed.
