### ISSUE TITLE
Attachements not showing skype side

### ISSUE THREAD

**Issue by arabek** [Infiziert90/Discord-Skype-Bot#9]
```python
Traceback (most recent call last):
  File "/home/user/.local/lib64/python3.6/site-packages/discord/client.py", line 251, in _run_event
    await coro(*args, **kwargs)
  File "/mnt/raid/ext/STUFF/src/user/src/Discord-Skype-Bot/discord_client.py", line 93, in on_message
    content = await self.to_skype_format(content, message)
  File "/mnt/raid/ext/STUFF/src/user/src/Discord-Skype-Bot/discord_client.py", line 275, in to_skype_format
    content += f"\n<a href=\"{word['url']}\">{word['filename']}</a>"
TypeError: 'Attachment' object is not subscriptable
```

Discord bot installed from git master, pip3 install -r requirements.txt

**Comment by ptyx11** [comment]
any update on this?
